name: Test SDK

on:
  #schedule:
  #  - cron: '0 13 * * *' # Runs every day at 7:00 AM CST (UTC-6)
  workflow_dispatch:

jobs:
  buildonlatest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, windows-latest, windows-2019, macos-13, macos-latest,ubuntu-24.04-arm,ubuntu-22.04-arm,windows-11-arm]    
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
          10.0.x
          3.1.x

  testonlatest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, windows-latest, windows-2019, macos-13, macos-latest,ubuntu-24.04-arm,ubuntu-22.04-arm,windows-11-arm]    
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@main
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
          10.0.x
          3.1.x
