name: test single architecture on windows

on: 
 push:

jobs:
  Defaultcheck:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: | 
            9.0.308
      -   run: |
           where.exe dotnet
           $env:PATH
           dotnet --info

  Archcheck:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: lmvysakh/setup-dotnet@support_architecture
        with:
         architecture : 'x86'
         dotnet-version: | 
                  9.0.308
      - run: |
         where.exe dotnet
         $env:PATH
         dotnet --info
