name: Test rollForward

on:
  push:
    branches:
      - t538

jobs:
  # rf-channel-sts:
  #   # name: "latestMajor + channel:STS | ${{ matrix.os }}"
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Install .NET
  #       run: |
  #         curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --skip-non-versioned-files --jsonfile ./global.json 
          
  #     # --version latest --channel STS 

  #     # - name: Setup dotnet
  #     #   uses: js6pak/setup-dotnet@feat/support-rollForward
  #     #   with:
  #     #     dotnet-version: latest
  #     #     dotnet-channel: STS
  #     #     global-json-file: ./subdirectory/global.json
      
  rf-dotnet-lmin:
    name: "latestMinor"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v6
      - name: Write global.json
        shell: bash
        run: |
          mkdir -p subdirectory
          echo '{"sdk":{"version":"3.0.100","rollForward":"latestMinor"}}' > ./subdirectory/global.json
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
        #   dotnet-version: latest
        #   dotnet-channel: STS
          global-json-file: ./subdirectory/global.json

  rf-dotnet-lmaj:
    name: "latestMajor"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v6
      - name: Write global.json
        shell: bash
        run: |
          mkdir -p subdirectory
          echo '{"sdk":{"version":"3.0.100","rollForward":"latestMajor"}}' > ./subdirectory/global.json
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
        #   dotnet-version: latest
        #   dotnet-channel: STS
          global-json-file: ./subdirectory/global.json

  rf-dotnet-lf:
    name: "latestFeature"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v6
      - name: Write global.json
        shell: bash
        run: |
          mkdir -p subdirectory
          echo '{"sdk":{"version":"3.0.100","rollForward":"latestFeature"}}' > ./subdirectory/global.json
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
        #   dotnet-version: latest
        #   dotnet-channel: STS
          global-json-file: ./subdirectory/global.json

  rf-dotnet-lp:
    name: "latestPatch"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v6
      - name: Write global.json
        shell: bash
        run: |
          mkdir -p subdirectory
          echo '{"sdk":{"version":"3.0.100","rollForward":"latestPatch"}}' > ./subdirectory/global.json
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
        #   dotnet-version: latest
        #   dotnet-channel: STS
          global-json-file: ./subdirectory/global.json
