name: test single architecture on windows

on: 
 push:

jobs:

  Archcheck:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [windows-latest]
            arch: ['x64','x86']
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
         dotnet --info
      - uses: lmvysakh/setup-dotnet@implement_architecture_support 
        with:
         architecture : ${{ matrix.arch }}
         dotnet-version: | 
                  9.0.308
                  
      - run: |
                 where.exe dotnet
                 $env:PATH
                 dotnet --info
