name: Test rollForward

on:
  workflow_dispatch:

jobs:
  rf-channel-sts:
    name: "latestMajor + channel:STS | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Write global.json
        shell: bash
        run: |
          mkdir -p subdirectory
          echo '{"sdk":{"version":"3.0.100","rollForward":"latestMajor"}}' > ./subdirectory/global.json
      - name: Setup dotnet
        uses: js6pak/setup-dotnet@feat/support-rollForward
        with:
          # dotnet-version: latest
          dotnet-channel: STS
          global-json-file: ./subdirectory/global.json
  
  rf-dotnet-sts:
    name: "latestMajor + channel:STS | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      # - name: Write global.json
      #   shell: bash
      #   run: |
      #     mkdir -p subdirectory
      #     echo '{"sdk":{"version":"3.0.100","rollForward":"latestMajor"}}' > ./subdirectory/global.json
      - name: Setup dotnet
        uses: actions/setup-dotnet@main
        with:
          # dotnet-version: latest
          dotnet-channel: STS
          global-json-file: ./subdirectory/global.json
